Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python

taf/APR/BED.py
This is a bugfix for a duplicated column. https://cms-dataconnect.atlassian.net/browse/MACDC-4412
bug
Ran test version of APR runner and verified row counts.
=> MACDC-4412 Fix duplicated REC_ADD_TS

taf/PRV/PRV02.py
We are changes some values that are meant to mean missing (long strings of 8s or 9s) in PRVDR_DBA_NAME on the PRV base file from an empty string to NULL values.
Bug
I created a Databricks Notebook to compare changes to the PRV02 segment (specifically the Prov02_Main_CNST view). The count of NULL PROV_DBA_NAME values was compared to (and matched) the corresponding production PRV run.
https://databricks-val-data.macbisdw.cmscloud.local/#notebook/644690
https://cms-dataconnect.atlassian.net/browse/MACDC-4276
=> MACDC-4276 PROV_DBA_NAME empty string to NULL

taf/APL/BASE.py, taf/APL/ENRLMT.py, taf/APL/LCTN.py, taf/APL/OA.py, taf/APL/SAREA.py, taf/APR/BASE.py, taf/APR/BED.py, taf/APR/ENR.py, taf/APR/GRP.py, taf/APR/IDT.py, taf/APR/LIC.py, taf/APR/LOC.py, taf/APR/PGM.py, taf/APR/TAX.py, taf/DE/DE.py, taf/DE/DE0001BASE.py, taf/MCP/MCP03.py, taf/MCP/MCP04.py, taf/MCP/MCP06.py, taf/MCP/MCP07.py, taf/PRV/PRV03.py, taf/PRV/PRV04.py, taf/PRV/PRV05.py, taf/PRV/PRV06.py, taf/PRV/PRV07.py, taf/PRV/PRV08.py, taf/PRV/PRV09.py, taf/PRV/PRV10.py, taf/UP/BASE_FNL.py, taf/UP/TOP.py
This changes REC_UPDT_TS to null for rows when a record is inserted, but not updated. Only metadata tables make use of this column.
bug
=> MACDC-4376 Change REC_UPDT_TS to be null on insert

taf/TAF_Grouper.py
This is a bug fix to change the source of TAF input data from a static S3 bucket used during development to DataConnect for the National Plan and Provider Enumeration System (NPPES) data. Claim and Provider file types are impacted by this change.
Bug fix
https://databricks-val-data.macbisdw.cmscloud.local/#notebook/1091477/command/1091496
https://cms-dataconnect.atlassian.net/browse/MACDC-4247
None
=> Fix incorrect NPI column name to NPPES

taf/APL/APL.py, taf/APR/APR.py, taf/DE/DE.py, taf/UP/UP.py
This is a bug fix to correct regular expressions responsible for identifying state-specific runs when determining high values for DA_RUN_IDs used as inputs to TAF annual file types.
Bug
I took SQL generated from the TAF library and reviewed within a Databricks Notebook and production Redshift in order to rule out any differences with regular expression behaviors. Then, I ran changes for North Carolina and confirmed state specific output appeared in corresponding max run ID views.
https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3638026
https://cms-dataconnect.atlassian.net/browse/MACDC-4777
None
_Credit to TMSIS PR template and …
=> MACDC-4777 Corrected State Specific RegExps

taf/IP/IP_Metadata.py, taf/LT/LT_Metadata.py, taf/OT/OT_Metadata.py, taf/RX/RX_Metadata.py, taf/TAF_Runner.py, taf/__init__.py
Fixes null SRVC_ENDG_DT_DRVD. https://cms-dataconnect.atlassian.net/browse/MACDC-4636
bugfix
Tested with the OT runner and verified SRVC_ENDG_DT_DRVD does not produce nulls. Run in question: https://databricks-val-data.macbisdw.cmscloud.local/#job/1018371421646275/run/8525670
=> MACDC-4636 Fix null SRVC_ENDG_DT_DRVD

taf/TAF_Runner.py
missing f-string indicator on line 279 (from previous bug-fix #41 )
typo fix on prior PR (#41 )
bug
running code on databricks notebook
no
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
=> Update TAF_Runner.py/SSN_IND, fix typo in previous PR (#41)

taf/TAF_Runner.py
corrected logging & display of preplan and segment processing
maintenance fix
Runner Notebooks and User provided notebook
No
=> MACDC-4784-last-best-variables-on-the-de-record-not-matching-when-current-year-has-null-values-but-previous-year-has-non-null

.databricks/notebooks/flat_files/Create TAF Flat Files.py
This is a bug fix to ensure that our TAF file names are compliant with the [shared CMS EFT service's standards](https://tmsis2.atlassian.net/wiki/spaces/DEV/pages/856130293/TAF+-+Knowledge+base). In summary, we must shorten the timestamp to seven bits from eight.
Bug
I made a change to the corresponding [Databricks Notebook](https://databricks-val-data.macbisdw.cmscloud.local/?#notebook/3660864/command/3660871) and updated the corresponding Python program (Create TAF Flat Files.py) that's committed to this branch to see the file diff.
The portion of code responsible for the timestamp portion of the TAF file name was ran in this [Databricks Notebook](https://databricks-val-data.macbisdw.cmscloud.local/?#notebook/3676977) and print statements were used to visually confirm timestamps changed …
=> MACDC-5365 Incorrect Timestamp values for TAF files

taf/OT/OTL.py
This is a fix to write procedure code modifiers as upper case (opposed to passing through what is in T-MSIS claim lines) to the TAF Outpatient/Other TOC claim line file type. The functionality was already in the library, so we just had to add a flag to the `var_set_type1` definition for impacted columns.
Bug
I ran the `OT Runner` Python program locally and compared generated SQL to confirm the only difference was passing procedure code modifiers to the `upper` SQL function. The `OTL` view was changed.
[https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3693295/command/3693298](Notebook)
https://cms-dataconnect.atlassian.net/browse/MACDC-5655
None
_Credit to TMSIS PR template …
=> MACDC-5655 Add upper flag to procedure modifiers

taf/LT/LTH.py
This is a fix to handle how default SAS dates (January 1, 1960) are handled in the Long-Term Care claims header file type.
Bug
I ran the Long-Term Care Databricks job for a given state (California) where we knew this issue existed.
https://databricks-val-data.macbisdw.cmscloud.local/#job/200471/run/12054141
When the job completed, I reviewed the outputted data using this Notebook (and confirmed no more default SAS dates in output):
https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3692682
https://cms-dataconnect.atlassian.net/browse/MACDC-5859
None
=> MACDC-5859 Fix default date handling

taf/BSF/BSF_Metadata.py
related issue: [MACDC-5725](https://cms-dataconnect.atlassian.net/jira/software/c/projects/MACDC/issues/MACDC-5725)
fix to properly reset dates older than 1/1/1600 to 12/31/1599 for all date columns identified in the BSF Technical Specification (3 total).
bug fix
reviewed SQL logic in databricks notebook, did _not_ run a full BSF build
requirements can be found in the BSF Technical Specification
NOTE: the BSF_Metadata attribute `output_columns` contains CAST expressions which may prevent conditional searching by column name alone
- [x ] Is the issue number and a short description in the subject line?
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a …
=> MACDC-5725 ancient dates - Update BSF_Metadata.py

taf/OT/OTL.py
This corrects a issue with the character casing of tooth number values from T-MSIS. In TAF, they should all be stored as upper case values, which can be accomplished by passing the upper flag to the `var_set_type1` definition
Bug
A wheel was built and copied to DBFS, then installed as a Notebook-scoped library [here](https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3694950/command/3695417)
https://cms-dataconnect.atlassian.net/browse/MACDC-5743
None
=> MACDC-5743 Add upper flag to correct tooth number

taf/TAF_Runner.py
During the monthly TAF run, we encountered conflicts with the claim runner jobs trying to write the CCS services and procedures data for each run. This data is static and does not change frequently (typically annually). Based on this, the save mode has been updated to `ignore` which is similar to a `CREATE TABLE IF NOT EXISTS` in SQL.
Bug
I tested this code by completing the monthly run with concurrent claim file types (IP, LT, the OT).
https://cms-dataconnect.atlassian.net/browse/MACDC-5510
None
=> MACDC-5510 Changed save mode to avoid conflicts

taf/DE/DE_Runner.py
When input data to the Annual Demographics and Eligibility process was reviewed, we noticed that the current year's Annual Demographics and Eligibility data was included as part of the process to identify maximum run ID values. This is not consistent with the current production process.
Bug
I visually compared the production SAS code to confirm generated SQL for each file type's maximum run IDs was consistent.
<details><summary>SQL Generated from production SAS code</summary>
```     %max_run_id(file=BSF, tbl=taf_mon_bsf);
%max_run_id(file=IP)
%max_run_id(file=LT)
%max_run_id(file=OT)
%max_run_id(file=RX)
%macro priorids;
%if &pyears. ne  %then %do;
%do p=1 %to %sysfunc(countw(&pyears.));
%let pyear=%scan(&pyears.,&p.);
%max_run_id(file=DE, tbl=taf_ann_de_base, inyear=&pyear.)
%end;
%end; …
```
=> MACDC-5638 Remove circular reference to current DE

taf/IP/IPH.py
In order to match production TAF data, we need to truncate DRG relative weights that have more than four decimal digits. In Databricks, type coercion rounds up which changes some relative weight values. 
Bug
A wheel was built with this commit included as part of May 2023's run. After that, the full file comparison yielded no differences in `TAF_COMPARE.__COMPARE_IPH`. Results were published to Confluence [here](https://cms-dataconnect.atlassian.net/wiki/spaces/TDRI/pages/25189842947/TAF+User+Acceptance+Testing).
https://cms-dataconnect.atlassian.net/browse/MACDC-5133
None
_Credit to TMSIS PR template and https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-pr …
=> MACDC-5133 Truncate DRG relative weights

taf/UP/BASE_IP.py, taf/__init__.py
This is a fix to date arithmetic used to trigger the creation of a second Inpatient stay based on admission and discharge dates.
Bug
I made the change locally and compared generated SQL for the corresponding CASE statement to confirm the correct positions for `CLAIM_ADMSN_DT` and `CLAIM_DSCHRG_DT_LAG`. After re-running the annual use and payment file type, I reviewed the [full file comparison data](https://cms-dataconnect.atlassian.net/wiki/spaces/TDRI/pages/25189842947/TAF+User+Acceptance+Testing) and confirmed `IP Stays` and `IP Days` were calculated consistently with production data.
https://cms-dataconnect.atlassian.net/browse/MACDC-6287
None
_Credit to TMSIS PR template and …
=> MACDC-6287 AUP Inconsistencies IP Stays and Days

.github/workflows/build-and-deploy.yml
This tweaks the slack message that goes to the [#dc-deploy channel in the DataConnect slack](https://dataconnect-workspace.slack.com/archives/C02QE4R4BPE) when the [TAF Build and Deploy job](https://github.com/Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python/actions/workflows/build-and-deploy.yml) runs.
It takes out the triggered by event line and makes the first line the link to the job.
Minor improvements
Well, I didn't because I don't want to trigger the deploy job, but the link is something we already do elsewhere, like with the secrets scan alerts.
Nope
=> MACDC-6394 Update TAF deploy slack alert

.databricks/notebooks/runners/up_runner.py, .databricks/notebooks/test_runners/up_runner.py, taf/TAF_Runner.py, taf/__init__.py
https://cms-dataconnect.atlassian.net/browse/MACDC-6306
This adds the metadata for the UP type.
5 columns in efts_fil_meta are nulled out. The metadata management process hasn't been documented yet but when this is decided on, those 5 columns will have to be taken into account.
Feature
https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3708857/command/3710223
Generated sql locally and executed it in this notebook.
=> MACDC-6306 Add metadata for UP

taf/DE/DE.py, taf/DE/DE0001BASE.py, taf/UP/BASE_FNL.py, taf/UP/TOP.py
https://jiraent.cms.gov/browse/DBDAART-2412
This is a bug fix for setting all timestamps to use EST. This will make timestamps consistent throughout the project. The old TAF system uses EDT which has a potential downside of having an ambiguous time during the fall time switch between 1 and 2 AM. EST does not follow daylight savings time and does not have this issue.
bug
=> DBDAART-2412 Set all timestamp updates to use EST

taf/BSF/BSF_Metadata.py
Misplaced comma prevented 'WVR_ID1' from being identified as a separate column that needs to be uppercased.
Originally the ticket has 88 columns with potential missing casing. All of these columns (except WVR_ID1) are in fact being cast as upper case in the FinalFormatter function in BSF_Metadata.py. There was an issue with WVR_ID1 because there was a misplaced comma in the output_columns list which prevented it from being identified and therefore uppercased.
Fix for DBDAART-2106
https://jiraent.cms.gov/browse/DBDAART-2106
Bug
Print out sql code (did not do a full run and write to data tables)
No
None
- [ x] Is the issue number and a short description in the subject line?
- [x ] I have …
=> Misplaced comma

taf/LT/LT.py, taf/LT/LTH.py, taf/LT/LTL.py, taf/LT/LT_Metadata.py, taf/TAF_Claims.py, taf/TAF_Grouper.py
This is field casing corrections to be in line with the original SAS code. This set of changes is related to Long Term header and line tables in the new system. Specifically the fields of ADJSTMT_IND and LINE_ADJSTMT_IND. In various sections of the code we've wrapped the fields with UPPER() function to force upper casing.
Bug/Maintenance
I've used the LT_Runner with a test case and reviewed the results of the SQL queries in the logs to show the fields.
No
None on a successful run.
=> DBDAART_2111 Casing corrections for ADJSTMT and LINE_ADJSTMT using upper()

taf/TAF_Grouper.py
Missing Taxonomy code to OTMTAX list was causing fields in OT and AUP to not match SAS.   Change is to add 101200000X to OTMAX list.
BUG
before and after sql attached to ticket. 
https://jiraent.cms.gov/browse/DBDAART-1483
None 
- [x ] Is the issue number and a short description in the subject line?
- [ x] My code follows the style guidelines of this project
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
_Credit to TMSIS PR …
=> DBDAART-1483  Added 101200000X to OTMTAX list

taf/IP/IP_Metadata.py
Fix for DBDAART-2110, 3 fields need upcasing to match SAS
bug
visual examination of before and after sql generated in Visual Studio.
Please see ticket here:
https://jiraent.cms.gov/browse/DBDAART-2110
- [x ] Is the issue number and a short description in the subject line?
- [ x] My code follows the style guidelines of this project
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
_Credit to TMSIS PR template and …
=> DBDAART-2110 Add 3 fields upper list IP_Metadata

taf/RX/RXL.py
Potential bug, found it in IPL fixed it there, saw it in RXL as well.
https://jiraent.cms.gov/browse/DBDAART-3601
No.
Before/After SQL attached to ticket.   Compared New RXL code to existing OTL/LTL code b/c they do the same thing.   Tested this change more extensively with a wheel file in IPL.
No
- [ N/A] I have commented my code, particularly in hard-to-understand areas
- [ N/A] I have made corresponding changes to the documentation
=> Changed date format for recoding Adj date to null

taf/IP/IPL.py
Bug - Adjudication Date values of 1960-01-01 are to be recoded to NULL, and this recode was not working properly.
https://jiraent.cms.gov/browse/DBDAART-3525
No
Before/After .sql attached to Jira ticket.   Created wheel with change, uploaded, and ran for month where the issue existed and verified that new python Adjudication date values matched SAS adjudication date values.  
Testing notebook here:   https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/4291831236183384/command/4291831236183836
No
- [ x] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=st …
=> DBDAART-3525 updated 01JAN1960 to 1960-01-01

taf/APL/APL_Runner.py, taf/APR/APR_Runner.py, taf/DE/DE_Runner.py, taf/TAF_Runner.py, taf/UP/UP_Runner.py
In taf_ann_inp_src, adds rec_add_ts and rec_updt_ts
In taf_ann_inp_src, sets src_fil_creat_dt to mm/dd/yyyy
In job_cntl_parms, fil_type is lower case
In several metadata tables, ITERATION is used over VERSION
In the last run of TAF, metadata was generated for the first time. In examining the metadata, several issues were identified and this PR addresses them.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-3603
This is a PR that primarily addresses formatting bugs in the TAF metadata. This does not expose anything else in our data that is not currently exposed.
Generated SQL for an annual and non-annual type and examined output
=> MACDC-3603 Fix several metadata issues

setup.py
While troubleshooting the wheel file creation process with a colleague, we noticed `setup.py` referenced the wrong location to populate the long description from `README.md`. Changing this to embed the description going forward.
None. This change should not introduce any additional security implications as it simply adds a textual description to the module used to build and distribute Python packages (not altering the pipeline in any meaningful way).
I ran `setup.py` locally and was able to successfully create a wheel file
No, the same process should be used to create a wheel file
=> [No Ticket] Fix TAF Long Description

taf/APL/APL.py, taf/APL/APL_Runner.py, taf/APR/APR.py, taf/APR/APR_Runner.py, taf/DE/DE_Runner.py, taf/UP/UP_Runner.py
This is a bug fix for a bug introduced in https://github.com/Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python/commit/65337715e68cdafc393a8e33ea481b738a44f6fa
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-3603
This is changing date formatting and does not expose any new data and does not affect infrastructure.
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/4252944469406616/command/4252944469406618
Generated sql and mocked test data in this notebook.
=> MACDC-3603 Fix date formatting for src_fil_creat_dt

taf/BSF/BSF_Metadata.py, taf/__init__.py
While reviewing the results of the September 2023 TAF run in DataConnect, discrepancies related to derived race and ethnicity information were discovered in the monthly Beneficiary summary data. The root cause of the issue was determined to be the absence of a "cleanser" definition to transform race code values to be padded with zeroes (consistent with several other code values). As a result, downstream indicators and flags were not assigned correctly. This change adds a "cleanser" specific to race codes to remediate impacted columns and their corresponding values.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4556
This change should not introduce any new security implications as we are transforming a value from T-MSIS data.
I tested this change by …
=> DBDAART-4556 Incorrect Race Codes and Flag

taf/BSF/BSF_Metadata.py, taf/__init__.py
While reviewing the results of the September 2023 TAF run in DataConnect, discrepancies related to care level status codes were discovered in the monthly Beneficiary summary data. The root cause of the issue was determined to be writing the incorrect column value to the final Beneficiary summary table. As a result, downstream indicators and flags were not assigned correctly. This change writes the correct, zero padded value to the final Beneficiary summary table.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4555
This change should not introduce any new security implications as we are transforming a value from T-MSIS data.
I tested this change by generating SQL for the impacted segment in my local development environment and comparing to September's …
=> DBDAART-4555 Fix reference to Care Level Status

taf/TAF_Runner.py
This is changing job_cntl_parms.job_parms_txt to use the last day of the month. The purpose of this is to match TAF in Redshift. Since the last day of the month is specified when doing job runs, this parameter can be used to insert into job_cntl_parms.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-3603
No new data is exposed from this change.
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#job/110491103788104/run/355360875546544
This run is executing metadata for da_run_id 9607. Looking at the job_cntl_parms after the run shows that job_parms_txt is 2023-06-30.
=> DBDAART-3603 Set job_cntl_parms job_parms_txt to last day of month

.github/CODEOWNERS
As part of larger on/offboarding discussions and review, it was discovered that offboarded people haven't been removed from CODEOWNERS files in the macdc repos.
This story is to review all macdc CODEOWNERS files and remove anyone not on the project.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4516
Removing accounts no longer on project improves security.
na
just the jira ticket
=> [DBDAART-4516] Update CODEOWNERS Remove old accounts

taf/OT/OTL.py
Reviewing results of the FFC of September's interim TAF run in DC, we noticed `TOOTH_NUM` values written to the Outpatient/Other claim lines file were no longer uppercase. This was previously addressed under [MACDC-5742](https://cms-dataconnect.atlassian.net/browse/MACDC-5743). Further investigation yielded that the `upper` flag was removed in the call to `var_set_type1` for `TOOTH_NUM` by [this](https://github.com/Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python/commit/6d8fe95ed345296714c44cfc23c911cd7265a7c2) commit. This change reverts impacted ETL for `TOOTH_NUM`
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4731
There are no new security implications from this change as this change transforms values from a existing query.
I generated the SQL …
=> DBDAART-4731 Add upper case flag to tooth numbers

taf/PRV/PRV05.py, taf/PRV/PRV08.py
to address the issue of long provider ID values, greater than 12 characters, in the PRV & APR Identity & Group segments
* Link to the Jira ticket for this change:  
<https://jiraent.cms.gov/browse/DBDAART-4575>
none
notebook in databricks VAL
no
=> DBDAART-4575 PRV & APR prvdr_id long values

taf/DE/DE_Runner.py
commenting out assignment of VERSION to 0 which leads to incorrect values in the DE_LINK_KEY field https://jiraent.cms.gov/browse/DBDAART-4762
to fix a bug in DE_LINK_KEY and ANN_DE_VRSN
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4762
no
initial investigation performed here: https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/2956054267841356
and another ticket, [DBAART-4787](https://jiraent.cms.gov/browse/DBAART-4787),has been opened to determine if further investigation is necessary
no
=> DBAART-4762 Fix DE Link Key

taf/UP/BASE_HDR_COMB.py, taf/__init__.py
While reviewing the results of the September 2023 TAF run in DataConnect, discrepancies with claim paid amounts were discovered in the annual Use and Payment data. The root cause of the issue was determined to be that the incorrect aggregation function was passed to the `TAF_Closure` definition. In this case, each claim type (IP, OT, LT, and RX) are combined using the maximum claim paid value rather than the summation of all types.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4580
This change should not introduce any new security implications as we are transforming a value from T-MSIS data.
A new wheel was built and deployed to [re-create](https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#job/202767374103997/run/81263759256360) …
=> DBDAART-4580 Incorrect Claim Aggregation in Use and Payment File

taf/IP/IPH.py, taf/LT/LTH.py, taf/OT/OTH.py, taf/RX/RXH.py
Recently we conducted a test with the CCW to confirm TAF flat files generated from DataConnect were syntactically correct and identical to a recent production run. Their results identified a discrepancy in our claim header data (IPH, OTH, LTH, and RXH) with `REC_UPDT_TS` values. We reached out to the production team to clarify and confirm our understanding of this data element. Then followed up with the CCW team to understand impacts to their pipeline. They expressed concern over this difference, so this change addresses that in our claim header data. During this time, I also noted a formatting difference to be addressed in a subsequent change.
SAS Code for Reference:
```
CONVERT_TIMEZONE('EDT', GETDATE()) AS REC_ADD_TS
CONVERT_TIMEZONE('EDT', GETDATE()) AS REC_UPDT_TS 
```
* Link to the …
=> DBDAART-4820 Assign REC_UPDT_TS in Claims Header data

taf/IP/IPL.py, taf/IP/IP_Metadata.py, taf/LT/LTH.py, taf/LT/LT_Metadata.py, taf/OT/OT_Metadata.py, taf/RX/RX_Metadata.py, taf/TAF_Claims.py, taf/TAF_Metadata.py
Because the data was originally being parsed by SAS, a null date was showing up as 01JAN1960 (epoch for sas dates). This date wasn't the format that python is looking for to coalesce for null dates. We've changed these to the proper format of 01-01-1960 from our incoming data. Keep in mind, while reviewing, that to_date() formats still remain as 1960-01-01
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-3572
No security implications. We're just modifying date formats.
I've set up a runner for the changes IP, LT, OT, and RX and called "view_plan()" to display the generated sql showing no 01JAN1960
See attached below:
[test_IP_Runner.py_.txt](https://github.com/Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python/files/13342607/test_IP_Runner.py_.txt) …
=> Modified dates for python coalesce 01-01-1960

.github/CODEOWNERS
In preparation for TAF PROD, we're making a modification to the CODEOWNERS file to add the TAF PROD users.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4917
There is always a security concern when modifying the CODEOWNERS file but we've recently changed the process to have 2 reviewers on a PR and the users added are part of the TAF project and given to us as stated in DBDAART-4917. There is one user who does not yet have a github account and will need to go through the project to get the job code and be added and approved with an additional PR from the TAF PROD team.
Verified the usernames from 4917
No.
=> Adding TAF PROD team users to github listed in DBDAART-4917

.github/CODEOWNERS
I have obtained the Github jobcode and have been added to the Mathematica TAF developers group. I updated the CODEOWNERS file to be added as an official code owner.
https://jiraent.cms.gov/browse/DBDAART-4917
NA
NA
NA
=> DBDAART-4917 Add Codeowner File

taf/DE/DE0002.py, taf/DE/DE0006.py
This addresses a potential issue when the `NUMBERS` and `NUMBERS_TWO` tables are created from some of the annual file type ETL. Only the Delta table format is supported for managed tables.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4966
This change should not introduce any new security implications since we are changing the table format only.
During December's run, I utilized [this](https://cms-dataconnect.cloud.databricks.com/?o=667862292061707#notebook/4328980751037945) notebook to create the `NUMBERS` and `NUMBERS_TWO` tables after the annual ETL dropped them. Since they existed at runtime, the SQL generated by the TAF Python library did not overwrite these definitions (so the Delta format was used in each run, not Parquet).
Successful job runs: …
=> DBDAART-4966 Change table type to Delta

taf/TAF_Closure.py
This change is to create a global function to set a field to null.
https://jiraent.cms.gov/browse/DBDAART-7438
N/A
before/after sqls with test usage attached to the ticket.
No
- [ n/a] I have made corresponding changes to the documentation
=> DBDAART-7483 - Added set_as_null function to TAF_Closure.py

.github/CODEOWNERS, taf/TAF_Metadata.py
Pulling changes from Main branch into CCB1.   These changes are:
1) Commit that removed DataConnect users from the codeowners file
2) Non-claim file submission for New Mexico
N/A
N/A
1) Visual inspection of the commit history, looking for inclusion of recent changes in from both CCB1 branch and Main such as those changes listed above from Main, and the set_to_null function from the CCB1 branch.
2) Ran IP claims through before and after whl files and did not find any differences in values.
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1735605711101549
=> Merge main into ccb1

taf/RX/RXH.py, taf/RX/RX_Metadata.py
CCB ticket calls for this field to be deprecated/set to null.  Leveraged TAF_Closure.set_as_null to set COPAY WAIVED IND to null upon extraction from T-MSIS, and var_set_type data cleaning function for this field in creation of view RXH.
https://jiraent.cms.gov/browse/DBDAART-7257
N/A
Visually examined the sql.   Ran TAF for test month/state before and after change, and compared all values before and after change.   All differences found in testing were expected.
Documentation team has already done their work.
- [x ] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guid …
=> Dbdaart 7257   rx  deprecate copay waived ind data element

taf/IP/IPH.py, taf/IP/IP_Metadata.py
Deprecate field per jira ticket.
https://jiraent.cms.gov/browse/DBDAART-7271
N/A
Visual examination of sql plan;   Visual examination of prior CCB1 commits in code;   Integration testing comparing CCB1, DEV and MAIN branches in this notebook:
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/850991985027102
Documentation team.
- [ x] I have made …
=> DBDAART-7271-IPH-Deprecate Referring Provider Type Code

taf/IP/IPH.py, taf/IP/IP_Metadata.py
Jira ticket to deprecate this field from CCB1 meeting.
https://jiraent.cms.gov/browse/DBDAART-7296
N/A
1) Visual Inspection of SQL plan before/after
2) Integration testing and comparison vs 2 other control runs.
3) Regression testing untouched fields.
For code merging:
1) Visually inspected code for prior CCB1 changes.
2) Leveraged github to compare to verify that DEV branch contains all CCB1 commits.
Please see jira ticket for more information on testing.
Documentation team doing this. 
- [x ] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guide)
- [x ] I have …
=> DBDAART-7296 - IPH - Deprecate RFRG_PRVDR_SPCLTY_CD

taf/IP/IPL.py, taf/IP/IP_Metadata.py
Deprecation of field from CCB1.
https://jiraent.cms.gov/browse/DBDAART-7265
N/A
See ticket for testing information. 
Visual Inspection of SQL plan before/after.
Visual inspection of code & Github compare for cumulative CCB1 changes
Integration and regression testing creating 1 month/1 state of TAF and comparing between MAIN, CCB1 and DEV branches.   All differences in results are expected. 
By documentation team
- [ x] I have commented my code, …
=> DBDAART-7265-IPL-Deprecate SRVCNG_PRVDR_TXNMY_CD

taf/OT/OTH.py, taf/OT/OT_Metadata.py
Jira ticket from CCB1 to deprecate this field.
https://jiraent.cms.gov/browse/DBDAART-7254
N/A
Visual inspection of sql plan before and after using VSCode DIFF.
Visual inspection of TAF code to verify field is not used downstream.
Merge Testing using Github interface and visual inspection of TAF code.
Integration and regression testing using a whl files from CCB1, DEV, and MAIN branches.      All integration testing passed.
Documentation team works on this. 
- [ x] I have performed a self-review of my own …
=> DBDAART-7254-OTH-Deprecate-RFRG_PRVDR_TXNMY_CD

taf/OT/OTH.py, taf/OT/OT_Metadata.py
CCB1 Ticket calls for deprecation of this field. 
https://jiraent.cms.gov/browse/DBDAART-7291
N/A
Visual Inspection of SQL plan changes;  
Integration and Regression testing in Notebook
Code merge testing and verification
See jira ticket for details.
=> DBDAART-7291-OTH-Deprecate-RFRG_PRVDR_SPCLTY_CD

taf/OT/OTH.py, taf/OT/OT_Metadata.py
Ticket to deprecate this field from CCB1.
https://jiraent.cms.gov/browse/DBDAART-7253
N/A
1) Visual inspection of sql plan
2) Visual inspection of subsequent calculations dependent on this field.
3) Code merge testing (visual inspection and Github DIFF)
4) Integration and regression testing between CCB1, Main, and DEV whl files.
All testing passed.   
Please see ticket for more testing information. 
Done by the documentation team. 
- [ x] I have commented …
=> DBDAART-7253-OTH-Deprecate-RFRG_PRVDR_TYPE_CD

taf/OT/OTH.py, taf/OT/OT_Metadata.py
Deprecate field ticket from CCB1
https://jiraent.cms.gov/browse/DBDAART-7278
N/A
1) Visual inspection of SQL plan after change.
2) Visual inspection of TAF code to verify no subsequent calculations rely on this field
3) Visual inspection and Github Interface code merge testing
4) Integration and regression testing in the notebook
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/3951363702250001
More testing detail in the ticket.  
- [ x] I have …
=> DBDAART-7278-OTH-Deprecate-PRVDR_UNDER_SPRVSN_TXNMY_CD

taf/OT/OTH.py, taf/OT/OT_Metadata.py
Jira ticket for deprecating this field from CCB1.
https://jiraent.cms.gov/browse/DBDAART-7287
N/A
Done by the documentation team.  
- [ x] I have performed a …
=> DBDAART-7287-OTH-Deprecate-PRVDR_UNDER_DRCTN_TXNMY_CD

taf/OT/OTH.py, taf/OT/OT_Metadata.py
CCB1 ticket to deprecate this field.
https://jiraent.cms.gov/browse/DBDAART-7255
N/A
Done by the documentation team. 
- [ x] I have performed a self-review of my own …
=> DBDAART-7255-OTH-Deprecate-PRVDR_UNDER_DRCTN_NPI_NUM

taf/OT/OTH.py, taf/OT/OT_Metadata.py
CCB1 ticket to deprecate this field
https://jiraent.cms.gov/browse/DBDAART-7298
N/A …
=> DBDAART-7298-OTH-Deprecate-CPTATD_AMT_RQSTD_DT

taf/OT/OTL.py, taf/OT/OT_Metadata.py
Ticket to deprecate this field from CCB1.
https://jiraent.cms.gov/browse/DBDAART-7297
N/A
2) Visual inspection of TAF code to determine how field used in subsequent calculations
5) Examined differences in downstream calculations based on this field.
- [ x] My …
=> DBDAART-7297-OTL-Deprecate-HCPCS_RATE

taf/OT/OTH.py, taf/OT/OT_Metadata.py
CCB1 ticket to deprecate this field. 
https://jiraent.cms.gov/browse/DBDAART-7268
N/A
Done by documentation team.  …
=> DBDAART-7268-OTH-Deprecate-CPTATD_PYMT_RQSTD_AMT

taf/IP/IPH.py, taf/IP/IP_Metadata.py, taf/OT/OTH.py, taf/OT/OT_Metadata.py, taf/RX/RXH.py, taf/RX/RX_Metadata.py
CCB1 ticket to deprecate this field in 3 files. 
https://jiraent.cms.gov/browse/DBDAART-7273
N/A
4) Integration and regression testing in 3 notebooks in the ticket.
RX:  https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/830475602231167
IP:  https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/830475602231214
OT: …
=> DBDAART-7273-RX-IP-OT-Deprecate-TOT_COPAY_AMT

taf/IP/IPH.py, taf/IP/IP_Metadata.py
jira ticket from CCB1 to add this field to TAF_IPH
https://jiraent.cms.gov/browse/DBDAART-6410
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/3103285964561156
Done by documentation team;
- [ x] My code …
=> DBDAART-6409-IP-Add-SOURCE-LOCATION

taf/IP/IPH.py, taf/IP/IP_Metadata.py
Ticket to add this field to IPH for CCB1.
https://jiraent.cms.gov/browse/DBDAART-7272
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/749353504980986
- [ x] The JIRA ticket number and a short description is in the …
=> DBDAART-7272-IPH-Add-TOT_BENE_DDCTBL_LBLE_AMT

taf/IP/IPH.py, taf/IP/IP_Metadata.py
CCB1 ticket to add field to TAF_IPH.
https://jiraent.cms.gov/browse/DBDAART-7263
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/4283577245627204
- [ x] My code follows …
=> DBDAART-7263-IPH-Add-TOT_BENE_COPMT_LBLE_AMT

taf/IP/IPH.py, taf/IP/IP_Metadata.py
CCB ticket to add this field to TAF_IPH;
https://jiraent.cms.gov/browse/DBDAART-7266
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/827478576407873
- [ x] My code …
=> DBDAART-7266-IPH-Add-TOT_BENE_COINSRNC_LBLE_AMT

taf/IP/IPH.py, taf/IP/IP_Metadata.py
CCB1 ticket to add this field to TAF_IPH.
https://jiraent.cms.gov/browse/DBDAART-7244
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/610324365427710
- [ x] My code …
=> DBDAART-7244-IP-Add-CMBND_BENE_CST_SHRNG_PD_AMT

taf/IP/IPH.py, taf/IP/IP_Metadata.py
CCB1 ticket to add this field.
https://jiraent.cms.gov/browse/DBDAART-7299
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/3038378600797121
- [ x] My code follows any …
=> DBDAART-7299-IP-ADD-SRVC_ENDG_DT

taf/LT/LTH.py, taf/LT/LT_Metadata.py
CCB1 ticket to add this field to TAF_LTH
https://jiraent.cms.gov/browse/DBDAART-7241
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/2400388842591129
Done by documentation team;
- [ x] My code follows …
=> DBDAART-7241-Add-TOT_BENE_DDCTBL_LBLE_AMT

taf/LT/LTH.py, taf/LT/LT_Metadata.py
CCB1 Ticket to add this field to TAF_LTH
https://jiraent.cms.gov/browse/DBDAART-7242
N/A
Done by documentation team;
- [ x] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20gui …
=> DBDAART-7242-LTH-Add-TOT_BENE_COPMT_LBLE_AMT

taf/LT/LTH.py, taf/LT/LT_Metadata.py
CCB1 ticket to add this field to TAF_LTH
https://jiraent.cms.gov/browse/DBDAART-7243
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1548729139548176
done by documentation team
- [ x] My code follows …
=> DBDAART-7243-LTH-Add-TOT_BENE_COINSRNC_LBLE_AMT

taf/LT/LTH.py, taf/LT/LT_Metadata.py
CCB ticket to add this field to TAF_LTH
https://jiraent.cms.gov/browse/DBDAART-7240
N/A
- [ x] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guid …
=> DBDAART-7240-LTH-Add-CMBND_BENE_CST_SHRNG_PD_AMT

taf/LT/LTL.py, taf/LT/LT_Metadata.py
Ticket to add this field to TAF_LTL for CCB.
https://jiraent.cms.gov/browse/DBDAART-7239
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/629232100828266
Done by the documentation team
- [ x] My code …
=> DBDAART-7239-LTL-Add-IHS_SVC_IND

taf/OT/OTH.py, taf/OT/OT_Metadata.py
Add field per CCB
https://jiraent.cms.gov/browse/DBDAART-11909
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/764203563393248
Done by the documentation team. 
- [ x] My code follows any applicable …
=> DBDAART-11909-OT-ADD-SRC_LCTN_CD

taf/OT/OTH.py, taf/OT/OT_Metadata.py
ticket to add field for CCB1
https://jiraent.cms.gov/browse/DBDAART-7262
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1300587598899103
- [ x] The JIRA ticket number and a short description is in the subject …
=> DBDAART-7262-OTH-Add-TOT_BENE_DDCTBL_LBLE_AMT

taf/OT/OTH.py, taf/OT/OT_Metadata.py
Ticket for CCB1 to add this field to TAF_OTH
https://jiraent.cms.gov/browse/DBDAART-7294
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/192022478934957
Done by documentation team;
- [ x] The JIRA ticket number and a short description is in the …
=> DBDAART-7294-OTH-Add-TOT_BENE_COINSRNC_LBLE_AMT

taf/OT/OTH.py, taf/OT/OT_Metadata.py
Ticket to add this field for CCB1 to TAF_OTH
https://jiraent.cms.gov/browse/DBDAART-7283
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/169264528363173
- [ x] The JIRA ticket number and a short description is in the …
=> DBDAART-7283-OTH-Add-CMBND_BENE_CST_SHRNG_PD_AMT

taf/OT/OTH.py, taf/OT/OT_Metadata.py
CCB1 ticket to add this field to TAF_OTH
https://jiraent.cms.gov/browse/DBDAART-7290
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/340557902541304 …
=> DBDAART-7290-OTH-Add-ORDRG_PRVDR_NPI_NUM

taf/OT/OTL.py, taf/OT/OT_Metadata.py
CCB1 ticket to add this field to TAF_OTL
https://jiraent.cms.gov/browse/DBDAART-7259
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/528549574430752
Done by documentation team …
=> DBDAART-7259-OTL-Add-IHS_SVC_IND

taf/RX/RXH.py, taf/RX/RX_Metadata.py
Ticket to add this field to TAF_RXH
https://jiraent.cms.gov/browse/DBDAART-6413
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1243570320250267
Done by the documentation teams. …
=> DBDAART-6413-RXH-Add-SRC_LCTN_CD

taf/RX/RXH.py, taf/RX/RX_Metadata.py
ticket to add this field to TAF_RXH
https://jiraent.cms.gov/browse/DBDAART-7289
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1880328405693198 …
=> DBDAART-7289-RXH-Add-TOT_BENE_DDCTBL_LBLE_AMT

taf/RX/RXH.py, taf/RX/RX_Metadata.py
Ticket to add this field to TAF_RXH for CCB1.
https://jiraent.cms.gov/browse/DBDAART-7282
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/4230741935527321
Done by the documentation team.  …
=> DBDAART-7282-RXH-Add-TOT_BENE_COPMT_LBLE_AMT

taf/RX/RXH.py, taf/RX/RX_Metadata.py
Ticket to add this field to TAF_RXH
https://jiraent.cms.gov/browse/DBDAART-7269
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1686720865826709 …
=> DBDAART-7269-RXH-Add-CMBND_BENE_CST_SHRNG_PD_AMT

taf/PRV/PRV10.py, taf/PRV/PRV_Runner.py, taf/TAF_Runner.py
Record counts by state for PRV_LOC were previously pulled from Prov03_Location_CNST, which does not
include dummy records created during the PRV_IDT,
PRV_LIC, and PRV_BED segments. Updated code
creates a new view with dummy records added, from
which record counts are computed.
=> Include dummy PRV_LOC records in efts_fil_meta.

taf/RX/RXL.py, taf/RX/RX_Metadata.py
CCB ticket to add this field to the TAF_RXL table.
https://jiraent.cms.gov/browse/DBDAART-7276
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/3655059236666053 …
=> DBDAART-7276-RXL-Add-IHS_SVC_IND

taf/IP/IPH.py, taf/IP/IP_Metadata.py
CCB1 ticket to change the format of this field.
https://jiraent.cms.gov/browse/DBDAART-5993
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/3277911998376746
Done by the documentation team; …
=> DBDAART-5993-IPH-Modify-DRG_RLTV_WT_NUM

taf/RX/RXL.py, taf/RX/RX_Metadata.py
CCB ticket to add this field to TAF_RXL.
https://jiraent.cms.gov/browse/DBDAART-7285
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/3265933013781605
Done by the documentation team …
=> DBDAART-7285-RXL-Add-INGRDNT_CST_PD_AMT

taf/RX/RXL.py, taf/RX/RX_Metadata.py
Ticket to add this field to TAF_RXL table.
https://jiraent.cms.gov/browse/DBDAART-7274
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/1575298146845235
N/A …
=> DBDAART-7274-RXL-Add-DSPNS_FEE_PD_AMT

taf/RX/RXL.py, taf/RX/RX_Metadata.py
CCB ticket to add this field to TAF_RXL
https://jiraent.cms.gov/browse/DBDAART-7264
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/701209836362926 …
=> DBDAART-7264-RXL-Add-PROFNL_SVC_FEE_PD_AMT

taf/APL/APL_Runner.py, taf/APR/APR_Runner.py, taf/DE/DE_Runner.py, taf/UP/UP_Runner.py
The annual runner code reads in column 'fil_cret_dt' from 'efts_fil_meta' table to create the new column 'src_fil_creat_dt'. The input column 'fil_cret_dt' is a string, not a date, which means the date() function is not applicable and why we are observing null values. Also, since 'fil_cret_dt' is already in 'mm/dd/yyyy' format, there is no need to apply date_format() function. Both of functions can be removed from the code. There is no need to change V5 DDL as it should be a string.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-10035
NA
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/740819107307326?o=955724715920583#command/740819107307335
NA
- [x ] My code …
=> DBDAART-10035-fix-null-values-in-SRC_FIL_CREAT_DT-in-taf-ann-inp-src

.github/CODEOWNERS
Add Celia Arsen and Nikki Cohen from Mathematica to CODEOWNERS 
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-10633
NA
I confirmed that the CODEOWNERS file is valid after adding both of them.
NA
=> DBDAART-10633-Add-additional-staff-to-codeowners

taf/OT/OTH.py, taf/OT/OTL.py, taf/OT/OT_Metadata.py
CCB2 Ticket to deprecate multiple fields in OTH and OTL
https://jiraent.cms.gov/browse/DBDAART-12840
N/A
Testing details in Jira ticket;
Visual Inspection of changes to SQL plan.
Code merge testing using Github UI.
Unit and regression testing in the following notebooks:
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/1356854838819139?o=955724715920583
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/2471317359912542?o=955724715920583
Done by documentation team. 
- [ x] I …
=> Dbdaart 12840 ot deprecate data elements

taf/RX/RXH.py, taf/RX/RXL.py, taf/RX/RX_Metadata.py
CCB2 deprecate ticket for these fields.
https://jiraent.cms.gov/browse/DBDAART-12842
N/A
Unit testing
Regression testing 
Visual inspection of before/after changes SQL plan
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/2996323169837246?o=955724715920583
=> DBDAART-12842 - RX - Deprecate Elements

taf/OT/OTH.py, taf/OT/OTL.py, taf/OT/OT_Metadata.py
Adapting multiple fields to the new T-MSIS V4 data for OT files. 
https://jiraent.cms.gov/browse/DBDAART-12843
https://jiraent.cms.gov/browse/DBDAART-13992
https://jiraent.cms.gov/browse/DBDAART-13997
- Visual inspection of before/after changes to the SQL Plan.
- Code Merge testing via Github interface.
- Unit testing where possible:   DX fields are nulled, Renamed CMS-64 field has values carried through but we don't have other data for A/B testing;   TMISIS V4 data did not have any of the Ordering Provider fields populated so could not test that these fields were carried through.
- [ x] My code …
=> DBDAART-12843; DBDAART-13992; DBDAART-13997

taf/OT/OT.py, taf/OT/OT_Metadata.py
Ticket to check if data are integer now and remove cast if they are;  Also updated dx_wide view name to be file type specific. 
https://jiraent.cms.gov/browse/DBDAART-14179
N/A
1) Code merge testing - all CCB2 commits included in this branch.
2) Visual inspection of SQL Plan changes.
3)  No changes to the output data were anticipated due to this change, so this notebook regression tests every field in OT vs. prior run, and no unexpected differences were found. 
New test run:
https://cms-dataconnect-val.cloud.databricks.com/jobs/686328978521045/runs/272348429624802?o=955724715920583
Regression test notebook:
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3554598965490599?o=9557247159205 …
=> DBDAART-14179- OT DX Remove Cast as Int, update DX_WIDE view name.

.github/README.md, taf/TAF_Runner.py, taf/__init__.py
Update the version using TAF software version instead of PI version in _init_.py
Parametrize the version column in TAF_runner to access the value set in _init_.py
* Link to the Jira ticket for this change: 
* https://jiraent.cms.gov/browse/DBDAART-14462
* https://jiraent.cms.gov/browse/DBDAART-14463
NA
Confirmed the new whl file has version "9.0" in it.
Uploaded the new .whl file to VAL and tested with OT job in taf schema v6, and confirmed the version column in both meta tables are correct now with "9.0".
=> DBDARRT 14462 & 14463 - Updated the version in README/ Source Code/Meta Tables

taf/OT/OT.py, taf/OT/OT_DX.py, taf/OT/OT_Runner.py
Adding exclusions from backfilling for nullness and admitting dx codes.
Also updated code to make references to global DGNS TYPE CODE valid values list stored in TAF_Metadata.py
https://jiraent.cms.gov/browse/DBDAART-14458
https://jiraent.cms.gov/browse/DBDAART-14341
N/A
1) Regression testing vs. CCB2 whl file - No unintended changes from this change found.
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3554598965490599?o=955724715920583
2) Scenario testing - No issues found:
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/1536460811690419?o=955724715920583
3)   Summary Stats - No issues found:
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/14375613 …
=> Dbdaart 14458 ot dx nullness and admitting type

taf/IP/IPL.py, taf/IP/IP_Metadata.py
Adding fields to TAF_IPL
https://jiraent.cms.gov/browse/DBDAART-12832
N/A
DDL:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3749055966763908?o=955724715920583
Regression Testing:   https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3749055966763897?o=955724715920583
Summary Stats/Nullness:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3749055966763911?o=955724715920583
Layout comparison in the jira ticket.
Done by the documentation team.  
- [ x] I …
=> DBDAART-12832- Add IPL Elements

taf/OT/OTL.py, taf/OT/OT_Metadata.py
Adding new elements to TAF_OTL file.
https://jiraent.cms.gov/browse/DBDAART-12836
N/A
Visual inspection of the changes to the SQL plan:
Elicited one unexpected change.   The SRVC_FAC_LCTN_ORG_NPI field is added to both the header and line level.   In the header specs, it is not upper cased.   In the line specs, it is upper cased.  When I added it to the upper list, because it has the same TMSIS name in header and line, the header field is now getting upper cased.   Note made in specs regarding this.   Leaving as both line and header being upper cased.
Regression Testing:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3867141456113353?o=955724715920583
Summary stats and nullness: …
=> DBDAART-12836 - OTL Adds

taf/TAF_Runner.py
Update to prmry_lang_cd in TAF_Runner.py
=> DBDAART-12789_BSF_Renames2

taf/BSF/BSF_Metadata.py
Move new vars in BSF_Metadata.py 'columns'
dictionary from ELG00004 to ELG00005.
=> DBDAART-13297_BSF_Add_Elig_Determinants2

taf/IP/IPH.py, taf/IP/IP_Metadata.py, taf/IP/IP_Runner.py, taf/LT/LTH.py, taf/LT/LT_Metadata.py, taf/LT/LT_Runner.py, taf/OT/OTH.py, taf/OT/OT_Metadata.py, taf/OT/OT_Runner.py, taf/RX/RX_Runner.py
Renaming fields to differentiate from line level fields with the same name.
https://jiraent.cms.gov/browse/DBDAART-14106
https://jiraent.cms.gov/browse/DBDAART-14107
N/A
DDL Changes:  
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/259667913688221?o=955724715920583
Visual inspection of the SQL Plan changes:  See attached before/after sqls on Jira ticket.
Regression Testing for 3 file types:
OT:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/259667913688222?o=955724715920583
IP:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/259667913688241?o=955724715920583
LT:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/259667913688232?o=9 …
=> Dbdaart 14106 rename ot ip lt elements

taf/FTX/FTX_Runner.py
Ticket to update all input constants to remove state_prod_catalog references.
https://jiraent.cms.gov/browse/DBDAART-14741
N/A
1) Visual inspection Before/After SQL plans, only change was the input catalog was removed.   Before/After sqls are attached to the jira ticket.
2) Conducted a new run w/ the new whl file:
https://cms-dataconnect-val.cloud.databricks.com/jobs/1020107592690136/runs/603976420793236?o=955724715920583
and regression tested against 1 month of the integration run, no differences found.
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/911384460274009?o=955724715920583
3) Code Merge testing - dev branch has all commits to CCB2.  See screenshot in jira ticket.
N/A
- [ x] …
=> DBDAART-14741

taf/IP/IPH.py, taf/IP/IP_DX.py, taf/LT/LTH.py, taf/LT/LT_DX.py, taf/OT/OTH.py, taf/OT/OT_DX.py, taf/RX/RX_DX.py
Valid value 3 for dgns cd indicators removed, these are no longer valid values. 
https://jiraent.cms.gov/browse/DBDAART-15350
N/A
Code merge testing, 
unit testing and regression testing in this notebook:  
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/407114359842575?o=955724715920583
No.
=> Dbdaart 15350 fix dgns cd ind
