Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python

taf/TAF_Claims.py

This is a fix for a TAF CLAIMS job runs. The table parameters were incorrect.
bug fix
I cloned the 4 Claims jobs that run and tested all 4 successfully with the change.
No.

Modified table parameter string to remove conditional

---

CODEOWNERS

This updates CODEOWNERS to add Matt Fury and remove Priyank Patel (as he is no longer active on the project).
Feature
No testing
No
None

Add Matt Fury to TAF project CODEOWNERS

---

build_whl.ps1
taf/UP/BASE_LT.py

Updated hardcoded values to variable (self.year)
Bug
Cloned the UP_Runner job and tested it through. Took a look at the output log and verified the table name change
No
No

MACDC-4126 - updated hardcoded year to self.year

---

CODEOWNERS

Adds RIE9-adhoc to codeowners file

Add RIE9-adhoc to CODEOWNERS

---

.databricks/notebooks/runners/apl_runner.py
.databricks/notebooks/runners/apr_runner.py
.databricks/notebooks/runners/bsf_runner.py
.databricks/notebooks/runners/de_runner.py
.databricks/notebooks/runners/ip_runner.py
.databricks/notebooks/runners/lt_runner.py
.databricks/notebooks/runners/mcp_runner.py
.databricks/notebooks/runners/ot_runner.py
.databricks/notebooks/runners/prv_runner.py
.databricks/notebooks/runners/rx_runner.py
.databricks/notebooks/runners/up_runner.py
.databricks/notebooks/test_runners/apl_runner.py
.databricks/notebooks/test_runners/apr_runner.py
.databricks/notebooks/test_runners/bsf_runner.py
.databricks/notebooks/test_runners/de_runner.py
.databricks/notebooks/test_runners/ip_runner.py
.databricks/notebooks/test_runners/lt_runner.py
.databricks/notebooks/test_runners/mcp_runner.py
.databricks/notebooks/test_runners/ot_runner.py
.databricks/notebooks/test_runners/prv_runner.py
.databricks/notebooks/test_runners/rx_runner.py
.databricks/notebooks/test_runners/up_runner.py

https://cms-dataconnect.atlassian.net/browse/MACDC-5004
Feature

MACDC-5004 Convert TAF notebooks to source files

---

taf/APL/APL_Runner.py
taf/APR/APR_Runner.py
taf/DE/DE_Runner.py
taf/IP/IP_Runner.py
taf/OT/OT_Runner.py
taf/PRV/PRV_Runner.py
taf/RX/RX_Runner.py
taf/TAF_Runner.py
taf/UP/UP_Runner.py

Making file version a parameter so it can be used properly and not hard-coded
feature
Validation here:
https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3660111/command/3660113
Successful run here:
https://databricks-val-data.macbisdw.cmscloud.local/#table/taf_python_v3/job_cntl_parms
Yes
None

Macdc 4610 file version column for all taf files

---

taf/BSF/BSF_Metadata.py
taf/BSF/ELG00018.py
taf/OT/OTH.py
taf/OT/OTL.py
taf/RX/RXH.py
taf/RX/RXL.py
taf/TAF_Grouper.py
taf/TAF_Runner.py

Addresses https://cms-dataconnect.atlassian.net/browse/MACDC-4635
bugfix
https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3666425/command/3666427 Completed a small run and verified that a query checking null vs typeof(null) gives the correct results.

MACDC-4635 Fix typeof(null) vs null

---

taf/TAF_Runner.py

Address issue in temporary table SSN_IND which leads to an error in the SSN Indicator flag for a state when the underlying value may be changing over time, e.g. `submtg_state_cd = '22'` (Louisiana),  
Fixes # **MACDC-4182** <https://cms-dataconnect.atlassian.net/jira/software/c/projects/MACDC/issues/MACDC-4182>
Please delete options that are not relevant.
Tested in shared databricks notebook: <https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3671007>
**Test Configuration**:
databricks environment: VAL
resolution for SSN_IND error, MACDC-4182
bug fix
Tested in shared databricks notebook: <https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3671007>
No.
bug in _BSF_Runner.py_, see [MACDC-5158](https://cms-dataconnect.atlassian.net/jira/software/c/projects/MACDC/issues/ …

Bug fix: MACDC-4182, fix error in SSN_IND (submtg_state_cd=22)

---

taf/LT/LTH.py

What is this?
Fixes dt fields to return original value if doesn't fit all cases in the statement
How would you classify this change (feature, bug, maintenance, etc.)?
bug fix
How did I test this (if code change)?
Multiple LT Runs with original some original states and run_ids
Is there accompanying documentation for this change?
No
Issues Encountered
None
Optional section to include any challenges encountered, options considered, and the approach chosen.
PR Checklist
[x] Is the issue number and a short description in the subject line?
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[x] I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
[x] My changes generate no …

MACDC-5099-Null-values-for-LTH-columns-svc_bgnng_dt-adjdctn_dt-and-svc_endg_dt_v2

---

taf/IP/IPH.py
taf/OT/OTH.py
taf/RX/RXH.py
taf/__init__.py

Additional header file fixes related to 5099 issue
bug fix
runners

MACDC-5299-null-values-for-header-file-columns-svc-bgnng-dt-adjdctn-dt-and-svc-endg-dt

---

taf/TAF_Metadata.py

Texas is going to be a CSO for eligibility only starting with the April 2023 monthly TAF run. To align with the current process in production, we must update TAF metadata to reflect this change. Code should not change as this is applied to T-MSIS data through a join
Maintenance
I ran the Python definition `getFormatsForValidationAndRecode` in the [Notebook ](https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3676948/command/3676976)and visually compared the contents of the `state_submsn_type` view with the corresponding data from Redshift attached in the [Jira ticket](https://cms-dataconnect.atlassian.net/browse/MACDC-5410).
Results here for comparison:
https://cms-dataconnect.atlassian.net/browse/MACDC-5410
N/A
*Optional section to include any challenges encountered, options …

MACDC-5410 Add CSO Handling for Texas Eligibility

---

taf/OT/OT.py

schema needs to be changed to tmsis on the aws_extract_line call
maintenance - change
schedule test runners
No

schema change to tmsis for aws_extract_line

---

taf/TAF_Grouper.py
taf/TAF_Runner.py
test/GrouperTest.py

Fix for parsing the ccs procs which are combined in the hcup table
bug fix
local tester and databricks runner
No
None

updates to TAF_Runner to parse ccs code up front

---

taf/APL/APL.py
taf/APR/APR.py
taf/BSF/BSF_Metadata.py
taf/IP/IPH.py
taf/IP/IPL.py
taf/LT/LTH.py
taf/LT/LTL.py
taf/MCP/MCP02.py
taf/MCP/MCP03.py
taf/MCP/MCP04.py
taf/MCP/MCP06.py
taf/OT/OTH.py
taf/OT/OTL.py
taf/PRV/PRV02.py
taf/PRV/PRV03.py
taf/PRV/PRV04.py
taf/PRV/PRV05.py
taf/PRV/PRV06.py
taf/PRV/PRV07.py
taf/PRV/PRV08.py
taf/PRV/PRV09.py
taf/PRV/PRV10.py
taf/RX/RXH.py
taf/RX/RXL.py
taf/TAF_Runner.py
taf/UP/UP.py

Fix for file_version and iteration. They are two separate things.
File Version is 2 characters
Iteration is I + File_Version
bug fix
ran a notebook to test file_version if not 2 characters.
Had to cast self.version as a string in case the version was a 2 character number without letters

changed test to 2 chars and added new self var self.ITERATION which adds I to self.VERSION

---

taf/__init__.py

This advances the version of the library to coincide with the current sprint in PI.02.
Maintenance
No test needed
No ticket
None

Advance version to current sprint

---

taf/OT/OT_Metadata.py

Addresses https://cms-dataconnect.atlassian.net/browse/MACDC-5745
Bugfix
Generated SQL before and after change. 
Executed here https://databricks-val-data.macbisdw.cmscloud.local/#notebook/3695012/command/3695029

MACDC-5745 Add different cleanser for OTL SRVC_ENDG_DT

---

taf/__init__.py

This advances the version of TAF to our current working sprint, PI02.03.
Maintenance
I was able to successfully build a wheel locally with this change, noting there was a warning because we're not compliant with PEP (to be resolved later).
No
None

[No ticket] Advance version to current working sprint

---

.github/workflows/build-and-deploy.yml

An immediate followup to PR https://github.com/Enterprise-CMCS/T-MSIS-Analytic-File-Generation-Python/pull/71 to tweak the slack message just a bit more.
Tweak
Ran the TAF Build and Deploy
Nope

MACDC-6394 Take the org/repo out of the Build and Deploy slack message

---

.databricks/notebooks/test_runners/ip_runner.py
.databricks/notebooks/test_runners/lt_runner.py
.databricks/notebooks/test_runners/ot_runner.py
.databricks/notebooks/test_runners/rx_runner.py
taf/IP/IP_Metadata.py
taf/TAF_Metadata.py
taf/TAF_Runner.py

Fixes Metadata so tables are written for runner metadata IP,LT,OT,RX
bug fix
Deployed test whls and went through runners and checked results
Only inline, there will need to be.
None

MACDC-6290 - Fixes for Metadata on IP,OT,RX,LT

---

taf/RX/RX_Metadata.py

Fixes for ticket DBDAART-2017, case differences in several fields.
bug
created before & after sqls in Visual Studio, examined changes.  
https://jiraent.cms.gov/browse/DBDAART-2107
- [x ] Is the issue number and a short description in the subject line?
- [ x] My code follows the style guidelines of this project
- [ x] I have added tests that prove my fix is effective or that my feature works
_Credit to TMSIS PR template and https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-yo …

DBDAART-2017 Add fields to upper list Rx_Metadata

---

taf/TAF_Runner.py

We had the wrong ccs proc table loaded during our latest runs and while our code was supposed to parse the table we had "ignore" during the run instead of "overwrite". We renamed the input table to clarify it and changed to overwrite during each run. While this table may not update frequently we don't know when it will so its safe to update during each run.
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-4577
There are no security implications because we're just modifying the  name of a table that is a readonly table for users.
Ran the notebook it stats only mode below. During the run() method you'll see the log information and that the notebook completed successfully.
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#job/489647748241833/ …

Updates to TAF Runner for CCS_SP_MAPPING table name and writing frequency

---

taf/IP/IPH.py
taf/LT/LTH.py
taf/OT/OTH.py
taf/RX/RXH.py

Adding valid value = 3 to be allowed to follow through for PYMT_LVL_IND.
https://jiraent.cms.gov/browse/DBDAART-5984
N/A
See Jira ticket for testing details;  
1) Visual inspection of changes to SQL plan
2) Integration testing with synthetic data in 4 file types
3) Integration testing with TMSIS data in 1 file type.
4) Regression testing all other fields in claims files.
5) Visually checked that DEV branch has cumulative CCB1 changes.
- [ x] I have performed a self-review of my …

Dbdaart 5984 add valid values to payment level ind

---

taf/IP/IPL.py
taf/IP/IP_Metadata.py

CCB1 Ticket to to add this field
https://jiraent.cms.gov/browse/DBDAART-7277
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/4382983864387617
Done by the documentation time.
- [ x] My code follows any …

DBDAART-7277-IPL-Add_IHS_SVC_IND

---

taf/OT/OTH.py
taf/OT/OT_Metadata.py

Ticket to add for CCB1
https://jiraent.cms.gov/browse/DBDAART-7293
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/4494060224074414
- [ x] …

DBDAART-7293-OTH-Add-TOT_BENE_COPMT_LBLE_AMT

---

taf/RX/RXH.py
taf/RX/RX_Metadata.py

Ticket to add this as part of CCB1.
https://jiraent.cms.gov/browse/DBDAART-7286
N/A
https://cms-dataconnect-val.cloud.databricks.com/?o=955724715920583#notebook/2558789397879904 …

DBDAART-7286-RXH-Add-RX_ORGN_CD

---

taf/RX/RX.py
taf/RX/RXH.py
taf/RX/RX_DX.py
taf/RX/RX_Metadata.py
taf/RX/RX_Runner.py

Adapting TAF RX to new T-MSIS input data structure.
https://jiraent.cms.gov/browse/DBDAART-12830  (create segment)
https://jiraent.cms.gov/browse/DBDAART-12837  (add dgns prsnt indicator to header)
N/A
Testing notebook:
https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/1733206071156365?o=955724715920583
1) Frequencies on new file
2) Missingness on new file
3) RX Link Key testing
4) dgns_prsnt field testing
5) Deep drive of randomly selected cases examining input and output data for the following situations:
a) where dgns_prsnt = 0
b) where dgns_prsnt = 1
6) Regression tested all header and line level fields before/after changes.
7) Code merge testing:  Github UI leveraged to confirm …

DBDAART-12830 - Create RX DX Segment/ Add Dgns Prsnt indicator to Header

---

taf/LT/LTH.py
taf/LT/LT_Metadata.py
taf/LT/LT_Runner.py
taf/TAF_Metadata.py

Adding new LT elements to TAF_LTH.
https://jiraent.cms.gov/browse/DBDAART-12833
N/A
Visual inspection of SQL plan before/after changes.
DDL notebook:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/739141436849502?o=955724715920583
Regression Testing:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/1733553323216702?o=955724715920583
Summary Stats/Nullness: https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/739141436849527?o=955724715920583
Comparison of Excel Layouts to DDL from taf_v6 w/ new fields in ticket.
Done by the documentation team.  
- [ x] My code follows any …

DBDAART-12833 -  Add LTH Elements

---

taf/RX/RXH.py
taf/RX/RX_Metadata.py
taf/RX/RX_Runner.py

Add new data elements to TAF_RXH table. 
https://jiraent.cms.gov/browse/DBDAART-12837
N/A
DDL:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3937073959127647?o=955724715920583
Regression testing:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3937073959127637?o=955724715920583
Summary Stats/Nullness:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3937073959127652?o=955724715920583#command/3937073959127659
Layout comparison in the jira ticket.
Done by the TAF documentation team. …

DBDAART-12837 Add RXH updates

---

.databricks/notebooks/flat_files/TAF Flat Files Columns.py
taf/DE/DE.py
taf/DE/DE0001BASE.py
taf/DE/DE_Runner.py

Ade denied dev

---

taf/RX/RXL.py
taf/RX/RX_Metadata.py

Adding elements to TAF_RXL table. 
https://jiraent.cms.gov/browse/DBDAART-12838
N/A
Visual inspection of changes to resolved SQL plan.   Before/After Sql attached to the ticket.  
Regression Testing:  https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3749055966764102?o=955724715920583
Summary Stats/Nullness: https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3668770622554225?o=955724715920583
DDL notebook: https://cms-dataconnect-val.cloud.databricks.com/editor/notebooks/3668770622554218?o=955724715920583
DDL comparison w/ layout file for new fields in Jira ticket.
Evidence of code merge test in Jira ticket.  
Done by documentation team. 
- [ x] The JIRA ticket number and …

Dbdaart 12838 add rxl elements

---

taf/BSF/BSF_Metadata.py
taf/BSF/ELG00005.py

Bsf remove masboe dev

---

.github/workflows/generate-codejson.yml
code.json

Complete SHARE IT compliance steps for T-MSIS-Analytic-File-Generation-Python
step 1 - step 4: add code.json and the GitHub Action to the repo, and create/review/merge the initial pull request
(Compliance Guide - https://confluenceent.cms.gov/pages/viewpage.action?spaceKey=MDSO&title=SHARE+IT+Compliance+Guide)
* Link to the Jira ticket for this change: 
https://jiraent.cms.gov/browse/DBDAART-15048
n/a
n/a
n/a

DBDAART 15048 Complete SHARE IT compliance steps

---

.github/workflows/generate-codejson.yml
code.json

Complete SHARE IT compliance steps for T-MSIS-Analytic-File-Generation-Python
step 1 - step 4: add code.json and the GitHub Action to the repo, and create/review/merge the initial pull request
(Compliance Guide - https://confluenceent.cms.gov/pages/viewpage.action?spaceKey=MDSO&title=SHARE+IT+Compliance+Guide)
* Link to the Jira ticket for this change: https://jiraent.cms.gov/browse/DBDAART-15048

DBDAART15048 Complete SHARE IT compliance steps 

---

code.json
taf/OT/OTL.py

rebasing my branch
[DBDAART-15686](https://jiraent.cms.gov/browse/DBDAART-15686): Fix and unit test the defect in mcp.py
none
N/A pulling in changes to main since I created my branch
updated MCP technical specs that clarifies record for fil_type ‘MCR’ is used to identify CSO (TAF MCP Technical Specifications_PI11.docx)
- [x ] My code follows any applicable [style guides](https://cms-dataconnect.atlassian.net/wiki/search?text=style%20guide)
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation

Rebase DBDAART-15686_MCP_CSOfix from Main
